### ISSUE TITLE
Bug: Negative credit card balance causes wrong "Debts" balance

### ISSUE THREAD

**Issue by 825i** [maybe-finance/maybe#1092]
**Describe the bug**
Setting a negative Credit Card balance subtracts the amount from debts incorrectly.

As Maybe counts a positive Credit Card balance as a loan/debt.

It should follow equal logic that a negative balance is understood as not owing anything/not counting as a debt.

In the screenshot below, me having -€4000 across my 2 credit cards actually means I don't owe anything out of a €2000 limit per card. Instead my debts on the right has had its total amount subtracted by €4000. It should still show €28,281.

**To Reproduce**
1. Set a negative balance for a credit card
2. Total debts is subtracted by that amount after all other calculations

**Expected behavior**
A negative balance should not count at all toward any debt reduction as it is not a reduction of debt but in fact a lack of debt.

**Screenshots / Recordings**
![Screenshot from 2024-08-15 09-53-37](https://github.com/user-attachments/assets/4ac31c22-6126-44fe-9bbc-13712d1384aa)

**Additional context**
It would be great in the future to set a "Credit limit" to properly see via graph etc. the percentage of debt remaining on a credit card. This would not only prevent this bug but introduce a great feature.

**Comment by zachgoll** [comment]
@825i currently, the system classifies all credit card accounts as a `liability` (aka "debt" in the UI).

I'm not sure I 100% agree with this because if you _overpay_ a credit card (negative balance), that overpayment will then be applied to reducing the future debt on that credit card account.

While I understand what you're getting at here, I'm worried this may be a bit counterintuitive for users.

I think our only alternative to this would be to reallocate this 4,000 to the "assets" category, which I'm not sure would be correct either since overpaying a credit card is not technically an "asset" (you generally can't go to the credit institution asking to withdraw that overpayment in cash).

The most important thing here is that `assets - debts = net worth`, and if we remove this from the calculation, the totals won't tie out properly.

**Comment by 825i** [comment]
Yeah I understand what you mean. I think it could maybe just be made slightly clearer in the UI eg.

"Input your credit limit"
"Input your current debt"
OR
"Input your remaining credit"

etc.

Something like this. It was just a bit weird that I put in a few cards that I don't owe anything on, so I put the limit of 2000 euro which is what I have remaining (2000/2000) and it showed me 2000 in debt.

I wanted my other credit cards (which I don't owe anything on) to also be seen as (other) assets. So I added them separately as an asset of 2000 each.

**Comment by zachgoll** [comment]
@825i got it, thanks for the feedback.  I agree that we could probably be more specific with labeling or tooltips to specify what that balance actually represents.

As of right now, "Balance" would represent "How much I currently owe" (not the credit limit) and represents a true "liability" on the user's balance sheet.
