### ISSUE TITLE
Improvement: Accounts in sidebar should be ordered the same as in the accounts summary page

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1294]
Currently, sidebar accounts and "accounts summary" accounts lists are not ordered the same.

We should order accounts either alphabetically or by value.

**Comment by gariasf** [comment]
I have been testing this and (briefly) and they seem ordered.
![image](https://github.com/user-attachments/assets/ef3218b7-9c4d-4fd1-8c12-b9934803a2c5)

Are there any specific steps to reproduce this issue?

**Comment by gariasf** [comment]
Oh, could this be the issue scenario?

![image](https://github.com/user-attachments/assets/4551b90b-42fd-41c1-80d4-433bd81c1bb5)

**Comment by ahatzz11** [comment]
In my case I use emojis on accounts and I think that ends up causing at least one issue, here's an example from my dummy accounts so far: 
<img width="858" alt="image" src="https://github.com/user-attachments/assets/053d952e-8eae-43a1-8c70-e763f385165d">


Personally I think the default should be alphabetical because sorting by value would mean the order can change over time which would be a bit annoying, but even better would being able to customize the order. I like to have things grouped together by 'type' vs just alphabetical, e.g. inside of "Investments" I usually go:
- brokerage/taxable accounts
- 401ks
- IRAs
- Other (529, HSA)

**Comment by zachgoll** [comment]
@ahatzz11 good points here.  I agree that alphabetical is better than size due to the consistency of that.

Would also be fairly easy to sort by `subtype`.

I'd say we hold off on custom sorting for now to keep it simple.
