### ISSUE TITLE
Bug: Transfer import

### ISSUE THREAD

**Issue by lo97** [maybe-finance/maybe#1365]
**Describe the bug**
Currently, I don't find a way to import transfer from one account to others, while it's possible to add them manually

**To Reproduce**
NA

**Expected behavior**
Have a csv import of transfers.

**What version of Maybe are you using?**
Self-hosted 0.1.0

**What operating system and browser are you using?**
Docker

**Comment by zachgoll** [comment]
@lo97 unfortunately due to the complexity of mapping transfers between accounts (that may or may not exist during the import), we're not support transfers during import at the moment.

The currently recommended guidance here is to import these transactions normally, then go to the "Transactions" page and mark them as transfers by selecting them:

![CleanShot 2024-10-25 at 09 05 27](https://github.com/user-attachments/assets/51a8b906-74e9-4c2c-bd47-f59f1799ff44)

We may be able to revisit this at a future time and build some CSV automation around it, but for now it is out of scope for us.
