### ISSUE TITLE
Bug: Adding transaction to crypto account should be similar with investment account

### ISSUE THREAD

**Issue by LeiShi1313** [maybe-finance/maybe#1465]
**Describe the bug**
A crypto transaction is similar with a investment transaction, the difference is that the price could be another ticket, for example, ETH-BTC

**To Reproduce**
1. Go to one of crypto account
2. Click on 'New'
3. See the modal

**Expected behavior**
A similar modal when adding new transactions in investment accounts

**What version of Maybe are you using?**
Self-hosted, 0.2.0-alpha.2

**Comment by zachgoll** [comment]
In order to have a fully featured view for crypto, we will need to:

- Enable support for a variety of crypto prices in Synth API 
- Build a tailored view (similar to investments) so that users can track crypto holdings
- Add the ability to link wallets / exchange holdings

Due to our lack of support for this, our current suggestion is to create a "value only" crypto account that tracks the overall value of all crypto owned: 

![CleanShot 2024-11-18 at 12 40 28](https://github.com/user-attachments/assets/131cbe7a-90ce-4502-bae5-cb2830b8c784)

This will allow you to include an approximate crypto value in your overall net worth while waiting for our official Crypto views.

We also have basic support for `BTC` currency exchange, so you can create a barebones setup as shown below where you track Bitcoin in one crypto account and "everything else" in another:

![CleanShot 2024-11-18 at 12 46 06](https://github.com/user-attachments/assets/45ce1359-9f13-4dd7-bbd0-4f01c2bcdfa7)

This is our recommendation for right now, but we do have "Crypto Views" on the roadmap:

https://github.com/maybe-finance/maybe/wiki/Roadmap
