### ISSUE TITLE
Add stories for client code

### ISSUE THREAD

**Issue by simonbukin** [maybe-finance/maybe#223]
We currently have Storybook integration set up for client code (`/apps/client`). However, to make this useful, we need to start implementing stories for the components/pages for that part of the app. This issue will track that work.

# `components`
- [x] APM.tsx
- [x] Maintenance.tsx
- [x] Meta.tsx 
# `components/account-views`
- [ ] DefaultView.tsx
- [ ] InvestmentView.tsx
- [ ] LoanView.tsx
# `pages`
- [x] 404.tsx
- [ ] data-editor.tsx
- [ ] index.tsx
- [ ] login.tsx
- [ ] oath.tsx
- [ ] onboarding.tsx
- [ ] register.tsx
- [ ] settings.tsx
- [ ] upgrade.tsx
# `pages/plans`
- [ ] [planId].tsx
- [ ] create.tsx
- [ ] index.tsx
# `pages/card`
- [ ] [id].tsx
# `pages/accounts`
- [ ] [accountId].tsx
- [ ] index.tsx

# Miscelleanous
- [ ] Migrate to TypeScript for Storybook files, which will allow us to use import aliases for `assets`
- [ ] Upgrade to Storybook 7. This is mostly an automatic process, but we need to spot check the design system and client Storybook to make sure nothing is impacted by the change 

The above is just a listing of all the pages/components found in `apps/client`. We can whittle down this list or add more, depending on our needs and what is feasible to encode into a story or not.

**Comment by anoopw3bdev** [comment]
@simonbukin Are contributions welcome for this issue? I would like to contribute

**Comment by simonbukin** [comment]
Contributions are welcome @anoopw3bdev! Let me know if you need any help with anything

**Comment by anoopw3bdev** [comment]
Cool @simonbukin I saw this draft PR https://github.com/maybe-finance/maybe/pull/229, should the new stories be written in top of this PR?

**Comment by simonbukin** [comment]
No, generally you would want to open a new PR for stories you’re adding. A good example of this is #226

**Comment by nikwhoa** [comment]
@simonbukin Are contributions welcome for this issue? I would like to contribute

**Comment by simonbukin** [comment]
@nikwhoa go for it! Contributions are welcome, let me know if you have any questions.

**Comment by tmyracle** [comment]
Meta and APM don't really warrant stories so marking those as done for now.

**Comment by SamuelFanawopo** [comment]
Exploring Storybook integration, I've hit a few roadblocks due to our client-side code and API setup. Our components and APIs are tightly interconnected, with diverse API interactions and complex state management. To effectively use Storybook, extensive mocking of API calls would be required using MSW (Mock Service Worker). This would involve creating handlers for each API endpoint, as shown below:

```jsx
// Example Mocks
const mockUseSession = () => ({ data: null });
const mockUseRouter = () => ({ push: () => {} });
const mockUseUserApi = () => ({
  useUpdateOnboarding: () => ({ mutateAsync: async () => {} }),
  useUpdateProfile: () => ({ mutateAsync: async () => {} }),
});
```
Creating these mocks, as illustrated in [this Storybook example](https://storybook.js.org/blog/build-a-nextjs-app-with-rsc-msw-storybook/), introduces a level of complexity and ongoing maintenance that may not be proportional to the benefits. The need to accurately mock each API endpoint risks inconsistencies with our backend, potentially leading to outdated or inaccurate testing scenarios. Additionally, creating simplified components exclusively for Storybook would lead to unnecessary duplication and maintenance challenges.

Integrating stories for the rest of our components and pages under these conditions could significantly increase complexity. However, I am open to suggestions and alternative approaches that might circumvent these issues.

**Comment by simonbukin** [comment]
Just a thought here, is it possible to transition some of these components to be purely presentational, and just pass props into them for easier integration with Storybook? This would be a pretty decent chunk of work, but I'm curious to hear some thoughts if we think the benefits are actually worth it.

I think that without some sort of isolated component testing framework like Storybook, issues like #139 are going to be much harder to track down and fix as the project grows. This is why I think refactoring some components to be less integrated with their associated APIs might be a viable path here.

**Comment by SamuelFanawopo** [comment]
Sounds like a good idea, leads to easier testing and debugging and will let us actually be able to create stories for all the components and pages. @tmyracle
