### ISSUE TITLE
Add new "Credit card" account form

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#329]
We're working on adding each new account type as they've got slightly different "field" needs.

All accounts have "Name" and "Balance" by default.

Additional fields:
* Type — Select (Mastercard, Visa, American Express, Discover)
* Limit — Number

View is in `/views/accounts/account/_credit.html.erb`

**Comment by sarvaiyanidhi** [comment]
Hi @Shpigford Can we use name as card_type instead of type as it throws error for using type as column name since it is reserved to check type in inheritance

`The single-table inheritance mechanism failed to locate the subclass: 'visa'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Account::Credit.inheritance_column to use another column for that information.`

**Comment by Shpigford** [comment]
@sarvaiyanidhi Yep, `card_type` is fine.

**Comment by sarvaiyanidhi** [comment]
@Shpigford Just to confirm, we need to add new 'limit' field in accounts table right? Just confirming as earlier I assumed that above fields needs to be added in account_credits table.

**Comment by Shpigford** [comment]
> @Shpigford Just to confirm, we need to add new 'limit' field in accounts table right? Just confirming as earlier I assumed that above fields needs to be added in account_credits table.

Yep, will need that new field!

**Comment by Shpigford** [comment]
@sarvaiyanidhi Let's put a pause on this for now as we've just started work on a new form for adding accounts that will likely replace a lot of work on this. Sorry about that!
