### ISSUE TITLE
Migrate from Next.js Pages to App router

### ISSUE THREAD

**Issue by coltonehrman** [maybe-finance/maybe#50]
*Not sure if this is a priority or not, but I personally would like to have App router vs Pages.*

https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#migrating-from-pages-to-app

**Comment by leerob** [comment]
There's an opportunity here to entirely remove the separate `server` package and [usage of tRPC](https://nextjs.org/docs/app/building-your-application/configuring/typescript#end-to-end-type-safety). There's a decent chunk of endpoints, but not a overwhelming amount. A lot of that extra "glue" code between client and server can be removed in the process of moving towards App Router + Server Components + Server Actions.

I noticed, for example, it's using the Pages Router patten of adding `getLayout` (which was the kind of hacky way of having layouts support before it was a built-in primitive). Now, it probably makes the most sense to [incrementally](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration) tackle this rather than doing it all at once.

For example, since most of the data fetching here seems to be client-side through custom React hooks, the first step of incremental adoption here would be to make the entry into the application (the top level `page`) as a Client Component with `"use client"`. 

I'm happy to answer questions and possibly even try to assist (or code review) in places here!

**Comment by tmyracle** [comment]
Hey @leerob stoked to see you here! Would definitely love your input and guidance as things continue to progress.

**Comment by Shpigford** [comment]
@ExplorerAadi My suggestion is to open a draft PR and outline your general gameplan on what work you plan on doing. Then others can add comments to that as well as review code changes as you're working on them.

**Comment by ExplorerAadi** [comment]
Thanks a lot @Shpigford . I was actually going through the app and noting down the point to plan the upgrade and then raise a better draft request.
