### ISSUE TITLE
When exchange rates are not available, foreign currency account rollups should show a warning UI + message

### ISSUE THREAD

**Issue by jakubkottnauer** [maybe-finance/maybe#724]
**Describe the bug**
The balance sums shown next to the collapsible account groups in the sidebar don't include accounts in foreign currencies, if today's exchange rates for those currencies are missing in the database.

**To Reproduce**
1. Create a new account in a foreign (= different from your base) currency (one that you haven't used before) with a non-zero balance
2. Observe that in the sidebar, the balance of the new account isn't included in the sum for that account type group

**Expected behavior**
Account group balances in the sidebar should take foreign currencies into account. In the screenshot below, the number next to `Other Liability` should be roughly `$1020.00` (200 SEK ~ 20 USD)

**Screenshots / Recordings**
<img width="321" alt="Screenshot 2024-05-07 at 22 31 03" src="https://github.com/maybe-finance/maybe/assets/113784/c6b06d60-8dbe-43d0-9744-75e08429082a">

**Additional context**
The issue is caused by a missing exchange rate when this check is performed: https://github.com/maybe-finance/maybe/blob/79789bd69630ad29d65b53f138da2ab6abaf69e4/lib/money.rb#L31

Perhaps we should sync the account right after it's created? Or at the very least call `account.sync_exchange_rates`. We'll also need to fetch exchange rates periodically or upon login, otherwise the bug reappears the next day.

**Comment by zachgoll** [comment]
@jakubkottnauer since populating exchange rates requires a user to _potentially_ spend money, the app needs to _assume_ that rates cannot always be populated in full and have sensible ways of handling that.

The behavior we're seeing here is the original intention, but may not be the best way to handle it.

What do you think is the best way to display the data when a user has not synced exchange rates?

**Comment by zachgoll** [comment]
I haven't quite gotten to this yet, but my thinking was that in these scenarios where **user action** is required to fix the data, we display global warnings to alert them that their data is not 100% correct and they need to do something to fix it:
![CleanShot 2024-05-08 at 08 40 08](https://github.com/maybe-finance/maybe/assets/16676157/e47ab306-ba99-4587-96db-288598e79ddd)

**Comment by jakubkottnauer** [comment]
Gotcha, yes, I think what you suggest would be fine. Maybe we could, in addition to the user action prompt, also show a little icon next to all the balances that are impacted by the missing exchange rate (as an example, in your screenshot the USD accounts in the sidebar would be shown normally, but foreign currency accounts would have the icon next to the balance)

**Comment by zachgoll** [comment]
@jakubkottnauer I'd agree with that—having granular "hints" that lead the user to full explanations / troubleshooting guides would be ideal here.

**Comment by erikaraujo** [comment]
Somewhat related to this, but is there (or is there a plan for it) a way to set the "default" currency?

The reason I think is related is: If I use this app only in BRL, I don't need an exchange rate in order to show the sum in the navbar.

**Comment by erikaraujo** [comment]
I don't know how the heck I missed that 🤦‍♂️

Thank you!

**Comment by Aubermean** [comment]
Most importantly, from a users perspective: how do I sync exchange rates?

**Comment by Aubermean** [comment]
Ok after some head scratching, what you need to do is add the Synth API key to the UI user preference page, and prompt to register and fill it in if its empty (otherwise multi currency won't work). I suppose if the whole app is going to depend on Synth it might be a good idea to keep nagging if the API key is empty, in the shortest term a solution could be to make an annoying banner warning if the app is launched without the env var.
