### ISSUE TITLE
Manually track US-based securities

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#752]
We currently allow you to track "Investment" accounts on a high-level "value of the account" basis.

This project is to add functionality to track that value based on real-time market data automatically.

It will currently be scoped to US-based securities (stocks + ETFs).

## Scope

- [ ] Instead of "Transactions," it should be "Holdings," where you'll explicitly pick a security and add the quantity, date and cost-basis
- [ ] Will use Polygon.io for data sourcing
- [ ] Should update periodically (once per day for self-hosters)
- [ ] UI/UX for changing amount of a holding. Needs to account for cost-basis.

**Comment by vanalmsick** [comment]
As I recently also started to work on a similar self-hosted personal finance tool, I compared data sources that provide rich comprehensive data but are also affordable.

I'd suggest to replace Polygon.io with FinancialModelingPrep.com because:

- Polygon.io does not have index constituent data - thus look-though analysis about largest underlies / countries / industries is not possible 
- pricing is similar
- FMP also has European/International data
- FMP has way more comprehensive data (e.g. company fundamental data, economic data, ESG data etc.) which might be very useful further down the line for risk management / portfolio optimisation tools

https://site.financialmodelingprep.com/developer/docs

I am also happy to contribute - just let me know on which component / feature I can help best 😄 👍

**Comment by zachgoll** [comment]
@vanalmsick thanks for the suggestion, I will look into it!  Long term I think we'll allow the self-hoster to choose their own data provider for this, so this initial build will be more about building the infrastructure to support that.

**Comment by zachgoll** [comment]
I'm going to close this issue out as I've scoped the deliverables to the "Portfolio Management" project linked below:

https://github.com/orgs/maybe-finance/projects/16
