### ISSUE TITLE
Make account "History" and "Transactions" sections more clear

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#838]
## Overview

It is currently a bit confusing looking at an account's "history" and "transactions":

![CleanShot 2024-06-05 at 16 36 23](https://github.com/maybe-finance/maybe/assets/16676157/af01b7ee-ceed-4d89-85f9-54ae4c198596)

![CleanShot 2024-06-05 at 16 36 54](https://github.com/maybe-finance/maybe/assets/16676157/160d5708-f72f-4090-9a7c-61e83f143a2e)

It is not clear to the user _how_ they should be _modifying_ the value of an account and how the changes they make _affect_ the account's value.

## Proposed solution

- Change "History" -> "Value" to clarify that this list is a history of account values over time
- Add daily balances to the "Value" tab (should match the line chart above)
  - We could remove duplicate balances if that's more clear? (i.e. when the account balance doesn't change day over day)
  - This will require a slight rework since currently, we're only displaying a list of `Valuation` records.  To maintain the editing UX, we'll have to change from displaying `Valuation` records to displaying `Account::Balance` records.  Since `Account::Balance` records should not be editable directly, this UX will act as a _proxy_ for editing `Valuation` records (i.e. if there is a `Valuation` on the date, modify it, otherwise, create it)

**Comment by flacnut** [comment]
My initial instinct is that having daily valuation at an account level is not very helpful. 

I recently ran into an issue, creating a real estate asset and then setting a valuation today, and a valuation 10 years ago. Selecting to view "all" history in the chart crashed the app.

History tab won't be useful for things like real estate, where the values change very rarely. 

For transactional accounts like credit cards or bank accounts, the history and the transaction pages make more sense to be merged.

For securities or crypto which do have daily valuation changes independent of buy/sell behavior (transactions), I can see value in a history tab. But is daily the right granularity here? Especially at > 1 year of history getting viewed. Is this history information helpful since we have the chart? What would be more useful I think is a stacked area chart option showing the contribution of each security to the overall up/down trend.

**Comment by zachgoll** [comment]
@flacnut I agree that we should consider deleting it altogether.  We can always add it back and early on it's probably best to error on the "minimalist" side until we're 100% clear what users find valuable.

To address a few specific points:

> I recently ran into an issue, creating a real estate asset and then setting a valuation today, and a valuation 10 years ago. Selecting to view "all" history in the chart crashed the app.

As this is more performance related, I wouldn't necessarily group this as something holding us back from showing a history.  But this is definitely worth a fix through either setting time series intervals or limiting the history we show.

> History tab won't be useful for things like real estate, where the values change very rarely.

In the future, I'm imagining that we'll allow users to connect a Zillow (or other 3rd party) valuation service and fetch an updated valuation every X weeks/months, which could be useful to see over time.

> For transactional accounts like credit cards or bank accounts, the history and the transaction pages make more sense to be merged.

Agreed.

> For securities or crypto which do have daily valuation changes independent of buy/sell behavior (transactions), I can see value in a history tab. But is daily the right granularity here? Especially at > 1 year of history getting viewed. Is this history information helpful since we have the chart?

All historical info is calculated and synced on a daily basis, so in _theory_, all the expensive work done here will happen in the background.  That said, I do agree that it adds some redundancy to the graph and may not be needed.
