### ISSUE TITLE
Error: 'container maybe-postgres-1 is unhealthy' when self-hosting with Docker

### ISSUE THREAD

**Issue by timoconnnor** [maybe-finance/maybe#938]
----------------------

**Is this issue related to a problem?  Please describe.**
I followed the steps to self-host using Docker, but it keeps showing "container maybe-postgres-1 is unhealthy." 

**Describe the work that needs to be done to address this issue**
I updated the Docker image to postgres and restarted containers using **docker-compose down -v** followed by **docker-compose up --build**.

**Additional context**

+ Steps Taken: Apart from updating and restarting containers, I also tried pulling the latest Docker image (docker-compose pull postgres:latest).
+ Error Messages: The logs show repeated occurrences of "exec /usr/local/bin/docker-entrypoint.sh: exec format error".
+ Expected Behavior: I expected the Postgres container to start without issues after updating the image.
+ Configuration Details: Running Docker version: Docker 26.1.4 on a Mac with Intel architecture.

**Comment by zachgoll** [comment]
@timoconnnor any chance you could share some additional logs surrounding the `exec format error` one?

**Comment by builtbyproxy** [comment]
I was experiencing this issue as well and have since fixed it. There are a couple of solutions to this:
1. My logs were saying my `postmaster.pid` had run out of space, so I gave it more space: 
![image](https://github.com/maybe-finance/maybe/assets/16897508/eed25109-4640-45eb-b1dc-863d3cd34847)
2. Sometimes my local postgres DB, outside of the maybe context runs out of space and get's real wonky. I 'fix' (idk if it's a good idea lol) this by removing the `.pid` and forcing postgres to regenerate it's `healthy state`. To do this for docker go to the files section of your container and then navigate to: 
`var/lib/postgresql/data` at the bottom of the file, delete the `postmaster.pid` file and then restart your container. 
![image](https://github.com/maybe-finance/maybe/assets/16897508/4da6c59f-f165-410c-8b67-b14b8bef3566)

It's worth noting, that between doing step 1 and then looking for the `.pid` file I've had another 4gb of docker storage consumed. So that's a bigger issue that might drive me insane 😅

**Comment by zachgoll** [comment]
@builtbyproxy yeah, resource contention is always a fun one with these types of bugs :) Ideally, running this app shouldn't cause too many problems like this so once we pinpoint what's causing this we'll get a fix in.

**Comment by builtbyproxy** [comment]
I've deleted my container for now and will come back another time. No matter what I've tried internally, `Maybe` is chewing my docker storage until my postgres refuses to start because it's out of space

**Comment by zachgoll** [comment]
@builtbyproxy just so I can get a better idea of what the problem is, are you saying that your _volume_ is filling up to 4GB almost instantly?
![CleanShot 2024-07-18 at 14 46 08@2x](https://github.com/user-attachments/assets/fd8f226b-fd5d-4dce-b91b-baee30029364)

What does your compose configuration look like?  And are you running several apps against this same Postgres service?  Or just Maybe?

**Comment by timoconnnor** [comment]
> @timoconnnor any chance you could share some additional logs surrounding the `exec format error` one?

```
(base) timoconnor@Tims-Air maybe % docker logs maybe-postgres-1

exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

Let me know if I'm doing something wrong, I just followed the instructions. Do other people host it with Docker and not have this issue?

**Comment by zachgoll** [comment]
@timoconnnor yes, Docker is fully supported.

Can you try updating your compose file to this and let me know if it works when restarted with `docker compose up -d --build`?

```yml
app:
  image: ghcr.io/maybe-finance/maybe:latest
  platform: linux/amd64 # <- add this
```

**Comment by timoconnnor** [comment]
I updated the docker-compose.yml file with the platform: linux/amd64 setting as suggested. Both the postgres and app containers started successfully, and postgres is now healthy. However, the app container continues to restart without providing any logs to diagnose the issue. The postgres issue is resolved, but I’m still encountering problems with the app container. Has this specific issue—where the app container isn't working and keeps restarting—occurred with anyone else? Any further insights or suggestions would be appreciated.
